### PR TITLE
Deploy CustomResources after dependencies

### LINKED ISSUE #670: Custom Resources often need secrets/config maps
# Bug report

Krane deploys priority resources in an order that doesn't make sense, given that CRs are likely to depend on other resource types such as Secrets or RBAC resources in order to transition to Ready.

**Expected behavior:** Krane should not deploy CRs until after Secrets, ConfigMaps, etc. The only thing that needs to come after CRs is Pods.

**Actual behavior:** Krane deploys CRs before the things they quite possibly depend on.

**Version(s) affected:** 1.1.0

### Steps to Reproduce

1. Deploy templates which include a Secret and a CR (eg usage of the percona-operator).

### PR DESCRIPTION
**Pull request by benlangfeld**
**What are you trying to accomplish with this PR?**

CustomResources are quite likely to depend on things like Secrets, RBAC resources or even PVCs. They should be available before blocking on monitoring the CustomResources for success.

Fixes #670

**How is this accomplished?**

This change ensures that CustomResources are pre-deployed after the other pre-deployed resource types.

**What could go wrong?**

WW3?

### CODE REVIEW

**Comment by benlangfeld** [comment]
Could someone please paste the test failure?

**Comment by dturn** [comment]
Tests passed, it shows failure, because of https://github.com/Shopify/krane/issues/506

**Comment by benlangfeld** [comment]
@dturn Might this be included in this week's release?

**Comment by dturn** [comment]
> Might this be included in this week's release?

Yes

**Pull request merged**
