### PR TITLE
Bump to 1.1.5

### PR DESCRIPTION
**Pull request by jpfourny**
**What are you trying to accomplish with this PR?**
Bump to 1.1.5

### CODE REVIEW

**Comment by timothysmith0609** [comment]
Hmm, this actually might be a minor version bump and not a patch version, since we've stopped supporting some deprecated fields and changed behaviour more than just bug fixing/patching. cc @kddeisz @RyanBrushett 

See #730 #738

**Comment by kddeisz** [comment]
Since we removed deprecated stuff, this should be major.

**Comment by timothysmith0609** [comment]
>Since we removed deprecated stuff, this should be major.

Sorry, yes you're absolutely right

**Comment by jpfourny** [comment]
What should the new version be? 2.0.0? 2.0.1?

**Comment by kddeisz** [comment]
`2.0.0`

**Comment by timothysmith0609** [comment]
Also you'll need to update the changelog and list out the breaking change explicitly. Also #730 is missing a changelog entry. From what I can see, the other outstanding PRs are mostly internal details like CI, etc., and we don't need to mention them

**Comment by jpfourny** [comment]
OK, I will update CHANGELOG for #730 #738 ;)

**Comment by jpfourny** [comment]
Closing this branch - will create another to cover major version bump 2.0.0.

**Comment by jpfourny** [comment]
PR for 2.0.0 bump: https://github.com/Shopify/krane/pull/744

**Pull request closed without merging**
