### PR TITLE
Ignore empty dry run errors

### PR DESCRIPTION
**Pull request by benlangfeld**
**What are you trying to accomplish with this PR?**

Fix https://github.com/Shopify/krane/issues/683#issuecomment-583858118

**How is this accomplished?**

Ignoring dry run failure with an empty error.

**What could go wrong?**

We might apply something that's broken. That's the best case scenario, since it's the only time we'd find out why it's broken.

### CODE REVIEW

**Comment by benlangfeld** [comment]
I'm unable to get minikube booted right now, so I can't deal with the tests for this.

**Comment by benlangfeld** [comment]
@dturn If that's the case, we should stop using dry-run, because it cannot be trusted. This is causing us regular deployment failures.

**Comment by dturn** [comment]
> we should stop using dry-run, because it cannot be trusted. 

Given the failures appear random, do you think retrying the command would be a viable fix?

**Comment by benlangfeld** [comment]
@dturn I hope that #705 is acceptable. It seems like it may be a sufficient solution for our case.

**Comment by benlangfeld** [comment]
Closing in favour of #705.

**Pull request closed without merging**
