### PR TITLE
Refactor/update attempts kubectl apply

### PR DESCRIPTION
**Pull request by rdji123**
Addressing context deadline issues associated with the [apply command](https://sh.splunk.shopifysvc.com/en-GB/app/search/causes_of_deploy_failures?form.time_field.earliest=-14d%40d&form.time_field.latest=now&form.repo=*)

Increasing the number of attempts on the apply command will not interfere with the syncing of resources I believe, as the resource watcher is initiated after the apply command and begins syncing [here.](https://github.com/Shopify/krane/blob/master/lib/krane/resource_deployer.rb#L128) As well any apply failures will be caught [here](https://github.com/Shopify/krane/blob/master/lib/krane/resource_deployer.rb#L161) reaching a DeploymentError before a sync. 

The Kubectl apply command is also idempotent, should be safe to retry.

### CODE REVIEW

**Comment by timothysmith0609** [comment]
This looks good to me except for the linter error in CI. Are you able to investigate that problem?

**Comment by timothysmith0609** [comment]
Ah, ok I'll take a look at fixing that, then. Sorry about that

**Comment by rdji123** [comment]
cc @Shopify/pipeline

**Review by ayatsynych — APPROVED** [review]
👏 let's see if with 2 reties we still see occurrences of this problem

**Review by timothysmith0609 — APPROVED** [review]

**Comment by ajshepley** [comment]
If you rebase with master, you'll get the rubocop changes/fixes.

**Comment by rdji123** [comment]
I rebased it! just waiting for to pass CI 🤞

**Pull request merged**
