### PR TITLE
Remove usage of deprecated_(timestamp,count) fields

### PR DESCRIPTION
**Pull request by douglas**
**What are you trying to accomplish with this PR?**

Do not use `deprecated` fields of k8s Events api.

**How is this accomplished?**

This PR just removes code that was added to handle a situation where `count` and `lastTimestamp` k8s fields where not available locally when running tests.

After investigation with Danny, seems the problem happens when you have a `minikube` cluster  with incompatible `client` and `server`, which was my case:

```bash
» kubectl --context minikube version                                                                               
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
``` 

**Update:** Actually, the real cause is that `Kubernetes 1.16.2` is affected by a bug as described [here](https://github.com/Shopify/krane/pull/666#issuecomment-575798448).

Which caused this:

Screen Shot 2020-01-16 at 4 22 13 PM

To fix it, I deleted my local cluster with `minikube delete` and recreated one with `dev up`, which gave me this:

```bash
» kubectl --context minikube version                                                                               
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Which made the test pass 👍 

Screen Shot 2020-01-16 at 4 25 43 PM

**What could go wrong?**

I can't think of any problem as our tests are running in `buildkite` and locally, but it should be easier to revert if we bump into a new problem.

### CODE REVIEW

**Comment by douglas** [comment]
Yes, it took me sometime yesterday to go to thought `Krane` source and `k8s` docs to ensure that weren't using `v1beta1`.

What I discovered is that when you use `kubectl get events` command as used in https://github.com/Shopify/krane/blob/master/lib/krane/kubernetes_resource.rb#L325 it will always use `apiVersion: v1`: 

```json
kubectl_1.16.2 get events -o=json --namespace=k8sdeploy-test-pvc-no-pv-f0090cb6f9122249 --context=minikube
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "count": 25,
            "eventTime": null,
            "firstTimestamp": "2020-01-17T04:56:28Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "Pod",
                "name": "pvc",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24498",
                "uid": "b8896365-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "kind": "Event",
            "lastTimestamp": "2020-01-17T04:56:55Z",
            "message": "0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:56:28Z",
                "name": "pvc.15ea93ac7757afb4",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24586",
                "selfLink": "/api/v1/namespaces/k8sdeploy-test-pvc-no-pv-f0090cb6f9122249/events/pvc.15ea93ac7757afb4",
                "uid": "b88a4b0a-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "reason": "FailedScheduling",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "default-scheduler"
            },
            "type": "Warning"
        },
        {
            "apiVersion": "v1",
            "count": 18,
            "eventTime": null,
            "firstTimestamp": "2020-01-17T04:56:27Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "with-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24481",
                "uid": "b7c97cdd-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "kind": "Event",
            "lastTimestamp": "2020-01-17T05:00:18Z",
            "message": "waiting for first consumer to be created before binding",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:56:27Z",
                "name": "with-storage-class.15ea93ac2c62f693",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24850",
                "selfLink": "/api/v1/namespaces/k8sdeploy-test-pvc-no-pv-f0090cb6f9122249/events/with-storage-class.15ea93ac2c62f693",
                "uid": "b7cad73a-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "reason": "WaitForFirstConsumer",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "persistentvolume-controller"
            },
            "type": "Normal"
        },
        {
            "apiVersion": "v1",
            "count": 1,
            "eventTime": null,
            "firstTimestamp": "2020-01-17T04:56:27Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "without-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24485",
                "uid": "b7cdf6f8-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "kind": "Event",
            "lastTimestamp": "2020-01-17T04:56:27Z",
            "message": "External provisioner is provisioning volume for claim \"k8sdeploy-test-pvc-no-pv-f0090cb6f9122249/without-storage-class\"",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:56:27Z",
                "name": "without-storage-class.15ea93ac302cf63d",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24492",
                "selfLink": "/api/v1/namespaces/k8sdeploy-test-pvc-no-pv-f0090cb6f9122249/events/without-storage-class.15ea93ac302cf63d",
                "uid": "b7d42761-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "reason": "Provisioning",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "k8s.io/minikube-hostpath 0ac870d5-38a3-11ea-be98-1a9a625dc63b"
            },
            "type": "Normal"
        },
        {
            "apiVersion": "v1",
            "count": 1,
            "eventTime": null,
            "firstTimestamp": "2020-01-17T04:56:27Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "without-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24488",
                "uid": "b7cdf6f8-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "kind": "Event",
            "lastTimestamp": "2020-01-17T04:56:27Z",
            "message": "waiting for a volume to be created, either by external provisioner \"k8s.io/minikube-hostpath\" or manually created by system administrator",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:56:27Z",
                "name": "without-storage-class.15ea93ac30334882",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24489",
                "selfLink": "/api/v1/namespaces/k8sdeploy-test-pvc-no-pv-f0090cb6f9122249/events/without-storage-class.15ea93ac30334882",
                "uid": "b7d3ec59-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "reason": "ExternalProvisioning",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "persistentvolume-controller"
            },
            "type": "Normal"
        },
        {
            "apiVersion": "v1",
            "count": 1,
            "eventTime": null,
            "firstTimestamp": "2020-01-17T04:56:27Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "without-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24485",
                "uid": "b7cdf6f8-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "kind": "Event",
            "lastTimestamp": "2020-01-17T04:56:27Z",
            "message": "Successfully provisioned volume pvc-b7cdf6f8-38e5-11ea-bfb2-1a9a625dc63b",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:56:27Z",
                "name": "without-storage-class.15ea93ac30cfc754",
                "namespace": "k8sdeploy-test-pvc-no-pv-f0090cb6f9122249",
                "resourceVersion": "24496",
                "selfLink": "/api/v1/namespaces/k8sdeploy-test-pvc-no-pv-f0090cb6f9122249/events/without-storage-class.15ea93ac30cfc754",
                "uid": "b7d6af79-38e5-11ea-bfb2-1a9a625dc63b"
            },
            "reason": "ProvisioningSucceeded",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "k8s.io/minikube-hostpath 0ac870d5-38a3-11ea-be98-1a9a625dc63b"
            },
            "type": "Normal"
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

But if you use `kubectl get events.events.k8s.io` then it uses `v1beta`, which then uses `deprecatedCount` and `deprecatedTimestamp`:

```json
» kubectl get events.events.k8s.io -o=json --namespace=k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0 --context=minikube --request-timeout=15
{
    "apiVersion": "v1",
    "items": [
        {
            "action": "",
            "apiVersion": "events.k8s.io/v1beta1",
            "deprecatedCount": 25,
            "deprecatedFirstTimestamp": "2020-01-17T04:41:19Z",
            "deprecatedLastTimestamp": "2020-01-17T04:41:48Z",
            "deprecatedSource": {
                "component": "default-scheduler"
            },
            "eventTime": null,
            "kind": "Event",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:41:19Z",
                "name": "pvc.15ea92d8cdd043b9",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23534",
                "selfLink": "/apis/events.k8s.io/v1beta1/namespaces/k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0/events/pvc.15ea92d8cdd043b9",
                "uid": "9aaf5d51-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "note": "0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.",
            "reason": "FailedScheduling",
            "regarding": {
                "apiVersion": "v1",
                "kind": "Pod",
                "name": "pvc",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23441",
                "uid": "9aae4d3e-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "reportingInstance": "",
            "type": "Warning"
        },
        {
            "action": "",
            "apiVersion": "events.k8s.io/v1beta1",
            "deprecatedCount": 20,
            "deprecatedFirstTimestamp": "2020-01-17T04:41:17Z",
            "deprecatedLastTimestamp": "2020-01-17T04:45:47Z",
            "deprecatedSource": {
                "component": "persistentvolume-controller"
            },
            "eventTime": null,
            "kind": "Event",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:41:17Z",
                "name": "with-storage-class.15ea92d880bfc55a",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23838",
                "selfLink": "/apis/events.k8s.io/v1beta1/namespaces/k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0/events/with-storage-class.15ea92d880bfc55a",
                "uid": "99eb1e7e-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "note": "waiting for first consumer to be created before binding",
            "reason": "WaitForFirstConsumer",
            "regarding": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "with-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23421",
                "uid": "99e93c27-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "reportingInstance": "",
            "type": "Normal"
        },
        {
            "action": "",
            "apiVersion": "events.k8s.io/v1beta1",
            "deprecatedCount": 3,
            "deprecatedFirstTimestamp": "2020-01-17T04:41:17Z",
            "deprecatedLastTimestamp": "2020-01-17T04:41:17Z",
            "deprecatedSource": {
                "component": "persistentvolume-controller"
            },
            "eventTime": null,
            "kind": "Event",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:41:17Z",
                "name": "without-storage-class.15ea92d88286c06c",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23431",
                "selfLink": "/apis/events.k8s.io/v1beta1/namespaces/k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0/events/without-storage-class.15ea92d88286c06c",
                "uid": "99ee4e21-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "note": "waiting for a volume to be created, either by external provisioner \"k8s.io/minikube-hostpath\" or manually created by system administrator",
            "reason": "ExternalProvisioning",
            "regarding": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "without-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23426",
                "uid": "99ec2cf9-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "reportingInstance": "",
            "type": "Normal"
        },
        {
            "action": "",
            "apiVersion": "events.k8s.io/v1beta1",
            "deprecatedCount": 1,
            "deprecatedFirstTimestamp": "2020-01-17T04:41:17Z",
            "deprecatedLastTimestamp": "2020-01-17T04:41:17Z",
            "deprecatedSource": {
                "component": "k8s.io/minikube-hostpath 0ac870d5-38a3-11ea-be98-1a9a625dc63b"
            },
            "eventTime": null,
            "kind": "Event",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:41:17Z",
                "name": "without-storage-class.15ea92d884393e84",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23434",
                "selfLink": "/apis/events.k8s.io/v1beta1/namespaces/k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0/events/without-storage-class.15ea92d884393e84",
                "uid": "99f3f387-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "note": "External provisioner is provisioning volume for claim \"k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0/without-storage-class\"",
            "reason": "Provisioning",
            "regarding": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "without-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23424",
                "uid": "99ec2cf9-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "reportingInstance": "",
            "type": "Normal"
        },
        {
            "action": "",
            "apiVersion": "events.k8s.io/v1beta1",
            "deprecatedCount": 1,
            "deprecatedFirstTimestamp": "2020-01-17T04:41:17Z",
            "deprecatedLastTimestamp": "2020-01-17T04:41:17Z",
            "deprecatedSource": {
                "component": "k8s.io/minikube-hostpath 0ac870d5-38a3-11ea-be98-1a9a625dc63b"
            },
            "eventTime": null,
            "kind": "Event",
            "metadata": {
                "creationTimestamp": "2020-01-17T04:41:18Z",
                "name": "without-storage-class.15ea92d8857b643a",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23438",
                "selfLink": "/apis/events.k8s.io/v1beta1/namespaces/k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0/events/without-storage-class.15ea92d8857b643a",
                "uid": "99f6aa66-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "note": "Successfully provisioned volume pvc-99ec2cf9-38e3-11ea-bfb2-1a9a625dc63b",
            "reason": "ProvisioningSucceeded",
            "regarding": {
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "name": "without-storage-class",
                "namespace": "k8sdeploy-test-pvc-no-pv-cfe011ad17574fc0",
                "resourceVersion": "23424",
                "uid": "99ec2cf9-38e3-11ea-bfb2-1a9a625dc63b"
            },
            "reportingInstance": "",
            "type": "Normal"
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```


**BUT** I just discovered that the go template is not compatible which `kubectl get events.events.k8s.io`, therefore, those fields aren't used at all from what I could research.

Besides all that, I feel that we had a bug in `krane` in the sense that tests are still passing if you change the `kubect get events` command to something like this:

```
    def fetch_events(kubectl)
      (...)
      out, _err, st = kubectl.run("get", "whatever", "--output=go-template=#{Event.go_template_for(type, name)}",
        log_failure: false, use_namespace: !global?)
      (...)
    end
```

Do you know or can think of a case that I didn't see? Thanks a lot for your help, Danny!

**Comment by KnVerey** [comment]
> What I discovered is that when you use kubectl get events command as used in https://github.com/Shopify/krane/blob/master/lib/krane/kubernetes_resource.rb#L325 it will always use apiVersion: v1:

I'm not really following this PR, but wanted to point out that experimentation is not going to give you an accurate result about this. The version that it uses is determined dynamically based on the information returned in discovery, i.e. what is enabled on a given server and in what order the GVs are listed. It's also possible it depends on the version of kubectl. You can force a particular GV to be used though, if you want to. Example: `kubectl get deployment.v1.apps`

**Comment by douglas** [comment]
After some more investigation, i.e, running `ruby -I test test/integration-serial/serial_deploy_test.rb -n test_pvc_no_pv` against different `kubernetes` servers and `kubectl` versions I discovered that the reason that it failed.

Kubernetes itself had a [bug](https://github.com/kubernetes/kubernetes/issues/83203) in version `1.16.2`, which was solved by [this](https://github.com/kubernetes/kubernetes/pull/83692), this explains why the tests are passing when I removed the deprecated fields handling logic in this PR.

I tested this code even in a Kubernetes 1.17 cluster and it is passing.

**Comment by dturn** [comment]
> kubectl versions since 1.13

We support 1.11 and higher for now https://github.com/Shopify/krane#installation.

>Kubernetes itself had a bug in version 1.16.2, which was solved by this pr.

The bug they're describing happens because they migrated to the group/version `events.k8s.io/v1beta1`, but its not supported everywhere (gke 1.15 for example). I was originally assuming `core/v1` was the latest version. While k8s hasn't issued any depreciation notices for `core/v1`, it feels like this PR is actually going the wrong direction since we currently support both group/version, but after this PR we will only support core/v1. 

Do you remember why we fall back to the depreciated fields? Was the issue that for sometimes series was empty?

**Comment by douglas** [comment]
I decided to close this PR because it wouldn't handle the case where `kubectl get events` use `events.events.beta.v1` API, which would make it which break, as discussed with @dturn.

Here is the discussion for context:

**Douglas:**

If I recall certain, the problem was because that specific test was not passing on my local environment and then you showed me how to fetch events using kubectl get events.events.k8s.io instead of kubectl get events and then I decided to support it - but the thing is that we actually use kubectl get events in our codebase as I mentioned in the PR, so actually, it wouldn’t use deprecated fields in any other situation besides this one

I don’t have much knowledge about kubernetes yet, so maybe you can see a scenario where it actually are used so I would love to learn more.

**Danny:**

`kubectl get . events.events.k8s.io`

forces kubectl to return events in the events.k8s.io group format.
However, I don't think kubectl get events actually forces kubectl to use the 'core' group, I think it lets the cluster choose the prefered version, I think we're now getting lucky that minikube and gke always use the core group. (edited) 

The tricky concept here Event has two ways it can be interacted with events.k8s.io/v1beta1 or v1  in the core group.
There are a bunch of Kinds in similar situation, like deployments in apps and extensions
But the 'prefered' version which is what kubectl uses is controlled by the cluster (for some reason I originally thought it was controlled by the kubectl version, but I don't think that's correct).
(...)
So my concern here is currently we can handle that order flipping, after your PR we wont be able to.

**Douglas:**

this is true, my only concern is that I don’t think it is just luck that the order isn’t flipping
otherwise the tests would be flaky, no?

**Danny**

Correct.
But say they do the flip in 1.18, we still have to support older versions since we currently support 1..11 through 1.16. So this PR feels like we're making the problem better today but isn't solving the problem in a forward compatible manner

**Douglas**

yup, I completely agree with that and will close the PR.

**Pull request closed without merging**
